version: "3"
services:
  nginx:
    build: ./docker/nginx
    ports: 
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
      - ./docker/nginx/logs:/var/log/nginx/
    networks:
      - internal
    depends_on:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./src/:/var/www/html/
      - ./docker/php/logs/php.log:/var/log/fpm-php.www.log
    networks:
      - internal
networks:
  internal:
    driver: bridge